import type { Ticket, User, DashboardStats } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Иван Петров",
    email: "ivan.petrov@stilt.com",
    phone: "+7-900-123-4567",
    role: "engineer",
    supportLevel: "L1",
    skills: ["network", "hardware", "email"],
    priority: 0,
    isActive: true,
  },
  {
    id: "2",
    name: "Мария Сидорова",
    email: "maria.sidorova@stilt.com",
    phone: "+7-900-234-5678",
    role: "engineer",
    supportLevel: "L2",
    skills: ["software", "database", "crm_system"],
    priority: 0,
    isActive: true,
  },
  {
    id: "3",
    name: "Алексей Козлов",
    email: "alexey.kozlov@stilt.com",
    phone: "+7-900-345-6789",
    role: "supervisor",
    supportLevel: "L2",
    isActive: true,
  },
  {
    id: "4",
    name: "Елена Волкова",
    email: "elena.volkova@stilt.com",
    role: "admin",
    isActive: true,
  },
]

export const mockTickets: Ticket[] = [
  {
    id: "1",
    number: "INC-2024-001",
    title: "Не работает интернет в офисе",
    description: "С утра пропал интернет во всем офисе. Сотрудники не могут работать.",
    type: "incident",
    status: "in_progress",
    priority: "high",
    category: "network",
    clientId: "c1",
    clientName: "Ольга Смирнова",
    clientEmail: "olga@client.com",
    clientPhone: "+7-900-111-2233",
    clientCompany: 'ООО "Клиент1"',
    assignedTo: "1",
    assignedToName: "Иван Петров",
    supportLevel: "L1",
    createdAt: new Date("2024-11-20T09:00:00"),
    updatedAt: new Date("2024-11-20T09:30:00"),
    slaDeadline: new Date("2024-11-20T13:00:00"),
    slaBreached: false,
    comments: [
      {
        id: "c1",
        ticketId: "1",
        userId: "1",
        userName: "Иван Петров",
        content: "Проверяю подключение к провайдеру",
        createdAt: new Date("2024-11-20T09:15:00"),
      },
    ],
  },
  {
    id: "2",
    number: "SR-2024-002",
    title: "Создание учетной записи для нового сотрудника",
    description: "Необходимо создать учетную запись для нового сотрудника Сергея Иванова.",
    type: "service_request",
    status: "assigned",
    priority: "medium",
    category: "software",
    clientId: "c2",
    clientName: "HR отдел",
    clientEmail: "hr@client.com",
    clientCompany: 'ООО "Клиент1"',
    assignedTo: "2",
    assignedToName: "Мария Сидорова",
    supportLevel: "L1",
    createdAt: new Date("2024-11-20T10:00:00"),
    updatedAt: new Date("2024-11-20T10:05:00"),
    slaDeadline: new Date("2024-11-20T18:00:00"),
    slaBreached: false,
  },
  {
    id: "3",
    number: "INC-2024-003",
    title: "Ошибка в CRM Bitrix24",
    description: "При попытке создать новую сделку выдает ошибку 500.",
    type: "incident",
    status: "escalated",
    priority: "critical",
    category: "crm_system",
    clientId: "c3",
    clientName: "Отдел продаж",
    clientEmail: "sales@client.com",
    clientCompany: 'ООО "Клиент2"',
    assignedTo: "2",
    assignedToName: "Мария Сидорова",
    supportLevel: "L2",
    createdAt: new Date("2024-11-20T08:00:00"),
    updatedAt: new Date("2024-11-20T11:00:00"),
    slaDeadline: new Date("2024-11-20T10:00:00"),
    slaBreached: true,
  },
  {
    id: "4",
    number: "INC-2024-004",
    title: "Не включается компьютер",
    description: "Рабочая станция не включается, индикатор питания не горит.",
    type: "incident",
    status: "active",
    priority: "medium",
    category: "hardware",
    clientId: "c4",
    clientName: "Петр Васильев",
    clientEmail: "petr@client.com",
    clientPhone: "+7-900-444-5566",
    clientCompany: 'ООО "Клиент3"',
    supportLevel: "L1",
    createdAt: new Date("2024-11-20T11:30:00"),
    updatedAt: new Date("2024-11-20T11:30:00"),
    slaDeadline: new Date("2024-11-20T19:30:00"),
    slaBreached: false,
  },
  {
    id: "5",
    number: "INC-2024-005",
    title: "Не приходит почта",
    description: "Не приходят письма на корпоративную почту с утра.",
    type: "incident",
    status: "resolved",
    priority: "high",
    category: "email",
    clientId: "c5",
    clientName: "Анна Кузнецова",
    clientEmail: "anna@client.com",
    clientCompany: 'ООО "Клиент1"',
    assignedTo: "1",
    assignedToName: "Иван Петров",
    supportLevel: "L1",
    createdAt: new Date("2024-11-20T08:00:00"),
    updatedAt: new Date("2024-11-20T10:00:00"),
    resolvedAt: new Date("2024-11-20T10:00:00"),
    slaDeadline: new Date("2024-11-20T12:00:00"),
    slaBreached: false,
  },
]

export const mockDashboardStats: DashboardStats = {
  totalTickets: 125,
  activeTickets: 23,
  assignedTickets: 15,
  inProgressTickets: 18,
  resolvedToday: 12,
  averageResolutionTime: 4.5,
  slaBreached: 3,
  engineerWorkload: [
    {
      engineerId: "1",
      engineerName: "Иван Петров",
      activeTickets: 5,
      avgResolutionTime: 3.8,
    },
    {
      engineerId: "2",
      engineerName: "Мария Сидорова",
      activeTickets: 7,
      avgResolutionTime: 5.2,
    },
  ],
}
